/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.datacontract.schemas._2004._07.usuariosdms.Usuario;
import org.tempuri.IAutenticacionVerificarExistenciaUsuarioUsuarioNoEncontradoExcepcionFaultFaultMessage;
import org.tempuri.IAutenticacionVerificarPasswordPasswordIncorrectaExcepcionFaultFaultMessage;

/**
 *
 * @author Max Ricardo
 */
public class LoginUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginUsuario
     */
    public LoginUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxUsuario = new javax.swing.JTextField();
        TxContrasena = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtIngresar = new javax.swing.JButton();

        TxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        BtIngresar.setText("Ingresar");
        BtIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(TxContrasena))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(BtIngresar)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addComponent(BtIngresar)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxUsuarioActionPerformed

    private void BtIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIngresarActionPerformed
        String usua = TxUsuario.getText();
        String password = TxContrasena.getText();
        Usuario verificado = new Usuario();
        int tipo = 0;
        try {
            verificado = verificarExistenciaUsuario(usua);
            try {
                tipo = verificarPassword(verificado, password);
                JOptionPane.showOptionDialog(this, "Autenticación existosa", "Login", JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Aceptar "}, "Cancelar");
                this.setVisible(false);
                
                
                
            } catch (IAutenticacionVerificarPasswordPasswordIncorrectaExcepcionFaultFaultMessage ex) {
                TxContrasena.setText("");
                JOptionPane.showOptionDialog(this, ex.getFaultInfo().getMensaje().getValue(), ex.getMessage(), JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "}, "Aceptar");
            }
        } catch (IAutenticacionVerificarExistenciaUsuarioUsuarioNoEncontradoExcepcionFaultFaultMessage ex) {
            TxUsuario.setText("");
            TxContrasena.setText("");
            JOptionPane.showOptionDialog(this, ex.getFaultInfo().getMensaje().getValue(), ex.getMessage(), JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Aceptar "}, "Cancelar");
            
        }
        
        System.out.println("El usuario " + verificado.getCodigo().getValue() + " es de tipo " + tipo);
    }//GEN-LAST:event_BtIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtIngresar;
    private javax.swing.JTextField TxContrasena;
    private javax.swing.JTextField TxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private static Usuario verificarExistenciaUsuario(java.lang.String usuario) throws IAutenticacionVerificarExistenciaUsuarioUsuarioNoEncontradoExcepcionFaultFaultMessage {
        org.tempuri.Autenticacion service = new org.tempuri.Autenticacion();
        org.tempuri.IAutenticacion port = service.getBasicHttpBindingIAutenticacion();
        return port.verificarExistenciaUsuario(usuario);
    }

    private static Integer verificarPassword(org.datacontract.schemas._2004._07.usuariosdms.Usuario usuarioConUsername, java.lang.String password) throws IAutenticacionVerificarPasswordPasswordIncorrectaExcepcionFaultFaultMessage {
        org.tempuri.Autenticacion service = new org.tempuri.Autenticacion();
        org.tempuri.IAutenticacion port = service.getBasicHttpBindingIAutenticacion();
        return port.verificarPassword(usuarioConUsername, password);
    }

}
